// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Car struct {
	ID        int64     `json:"id"`
	CarType   string    `json:"car_type"`
	CarModel  string    `json:"car_model"`
	CarImage  string    `json:"car_image"`
	CreatedAt time.Time `json:"created_at"`
}

type Driver struct {
	ID                   int64     `json:"id"`
	HashedPassword       string    `json:"hashed_password"`
	FullName             string    `json:"full_name"`
	DrivingLicense       string    `json:"driving_license"`
	Mobile               string    `json:"mobile"`
	CarID                int64     `json:"car_id"`
	CarType              string    `json:"car_type"`
	CarImage             string    `json:"car_image"`
	OnlineStatus         bool      `json:"online_status"`
	Rating               int32     `json:"rating"`
	ProfileStatus        int32     `json:"profile_status"`
	SubscriptionStatus   bool      `json:"subscription_status"`
	SubscriptionPackage  string    `json:"subscription_package"`
	SubscriptionAmount   string    `json:"subscription_amount"`
	SubscriptionValidity int32     `json:"subscription_validity"`
	SubscriptionExpireAt time.Time `json:"subscription_expire_at"`
	PasswordChangedAt    time.Time `json:"password_changed_at"`
	CreatedAt            time.Time `json:"created_at"`
}

type Fare struct {
	ID        int64     `json:"id"`
	Base      int32     `json:"base"`
	PerKm     int32     `json:"per_km"`
	PerMin    int32     `json:"per_min"`
	CreatedAt time.Time `json:"created_at"`
}

type Passenger struct {
	ID                int64     `json:"id"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	Rating            int32     `json:"rating"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type Subscription struct {
	ID                   int64  `json:"id"`
	SubscriptionPackage  string `json:"subscription_package"`
	SubscriptionAmount   string `json:"subscription_amount"`
	SubscriptionValidity int32  `json:"subscription_validity"`
	Status               bool   `json:"status"`
}

type Trip struct {
	ID              int64          `json:"id"`
	BookingID       string         `json:"booking_id"`
	TripStatus      string         `json:"trip_status"`
	PickupLocation  string         `json:"pickup_location"`
	PickupLat       string         `json:"pickup_lat"`
	PickupLong      string         `json:"pickup_long"`
	DropoffLocation string         `json:"dropoff_location"`
	DropoffLat      string         `json:"dropoff_lat"`
	DropoffLong     string         `json:"dropoff_long"`
	DriverID        sql.NullInt64  `json:"driver_id"`
	DriverName      sql.NullString `json:"driver_name"`
	DriverMobile    sql.NullString `json:"driver_mobile"`
	CarID           sql.NullInt64  `json:"car_id"`
	CarType         sql.NullString `json:"car_type"`
	CarImage        sql.NullString `json:"car_image"`
	Fare            sql.NullInt32  `json:"fare"`
	CreatedAt       time.Time      `json:"created_at"`
}
